# 端口
httpport: 3000
mode: "release"
debuglog: true
tracelog: true
logfile: ""
loglevel: "info"
logcount: 5
dbmode: "mysql"
mysql:
  # 数据库url
  url: master1
  port: 30006
  password: 123456
  username: root
  db: microshop
